### ISSUE TITLE
Write the ske-backend plugin

### ISSUE THREAD

**Issue by richcooper95** [richcooper95/test-repo#2]
### Description

Write a backend plugin for Backstage, which enables communication between Backstage and Kratix via a SKE GitOps state store.

### Tasks

- [ ] Create the plugin skeleton
- [ ] Create a `ske:configure-resource` Backstage action
- [ ] Support creation of resources via `ske:configure-resource`
- [ ] Support retrievals, updates, and deletes of resources via `ske:configure-resource`
